fix: Add esm module type to package.json to resolve import errors
Without the change, the importing of named exports causes runtime errors;
SyntaxError: The requested module '@danielxceron/youtube-transcript'
does not provide an export named 'YoutubeTranscript'...